services:
  repo:
    build: .
    container_name: raspilab-deb-repo
    volumes:
      - deb-repo:/repo
    ports:
      - "8000:8000"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  deb-repo:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/yocto/rpi-build/tmp/deploy/deb
